# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created: Thu Jun 30 22:58:34 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Sonos_Controller(object):
    def setupUi(self, Sonos_Controller):
        Sonos_Controller.setObjectName("Sonos_Controller")
        Sonos_Controller.resize(817, 692)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Sonos_Controller.sizePolicy().hasHeightForWidth())
        Sonos_Controller.setSizePolicy(sizePolicy)
        Sonos_Controller.setMinimumSize(QtCore.QSize(500, 0))
        Sonos_Controller.setBaseSize(QtCore.QSize(150, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Downloads/sonos_114px_1106655_easyicon.net.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Sonos_Controller.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(Sonos_Controller)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox = QtGui.QCheckBox(self.centralwidget)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 4, 1, 2)
        self.playPauseButton = QtGui.QPushButton(self.centralwidget)
        self.playPauseButton.setMinimumSize(QtCore.QSize(48, 48))
        self.playPauseButton.setMaximumSize(QtCore.QSize(48, 48))
        self.playPauseButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playPauseButton.setIcon(icon1)
        self.playPauseButton.setIconSize(QtCore.QSize(32, 32))
        self.playPauseButton.setObjectName("playPauseButton")
        self.gridLayout.addWidget(self.playPauseButton, 0, 8, 1, 1)
        self.volumeBar = QtGui.QSlider(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volumeBar.sizePolicy().hasHeightForWidth())
        self.volumeBar.setSizePolicy(sizePolicy)
        self.volumeBar.setMinimumSize(QtCore.QSize(120, 0))
        self.volumeBar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.volumeBar.setBaseSize(QtCore.QSize(150, 0))
        self.volumeBar.setOrientation(QtCore.Qt.Horizontal)
        self.volumeBar.setObjectName("volumeBar")
        self.gridLayout.addWidget(self.volumeBar, 0, 12, 1, 3)
        self.timeInSongLabel = QtGui.QLabel(self.centralwidget)
        self.timeInSongLabel.setText("")
        self.timeInSongLabel.setObjectName("timeInSongLabel")
        self.gridLayout.addWidget(self.timeInSongLabel, 3, 14, 1, 1)
        self.prevButton = QtGui.QPushButton(self.centralwidget)
        self.prevButton.setMinimumSize(QtCore.QSize(30, 30))
        self.prevButton.setMaximumSize(QtCore.QSize(32, 16777215))
        self.prevButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/prev.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prevButton.setIcon(icon2)
        self.prevButton.setIconSize(QtCore.QSize(20, 20))
        self.prevButton.setObjectName("prevButton")
        self.gridLayout.addWidget(self.prevButton, 0, 7, 1, 1)
        self.myQueueLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.myQueueLabel.setFont(font)
        self.myQueueLabel.setObjectName("myQueueLabel")
        self.gridLayout.addWidget(self.myQueueLabel, 5, 4, 1, 2)
        self.queueList = QtGui.QListWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.queueList.sizePolicy().hasHeightForWidth())
        self.queueList.setSizePolicy(sizePolicy)
        self.queueList.setObjectName("queueList")
        QtGui.QListWidgetItem(self.queueList)
        self.gridLayout.addWidget(self.queueList, 7, 4, 1, 11)
        self.nextButton = QtGui.QPushButton(self.centralwidget)
        self.nextButton.setMinimumSize(QtCore.QSize(30, 30))
        self.nextButton.setMaximumSize(QtCore.QSize(30, 30))
        self.nextButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextButton.setIcon(icon3)
        self.nextButton.setIconSize(QtCore.QSize(20, 20))
        self.nextButton.setObjectName("nextButton")
        self.gridLayout.addWidget(self.nextButton, 0, 9, 1, 1)
        self.sleepTimerLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.sleepTimerLabel.setFont(font)
        self.sleepTimerLabel.setObjectName("sleepTimerLabel")
        self.gridLayout.addWidget(self.sleepTimerLabel, 5, 9, 1, 1)
        self.servicesTree = QtGui.QTreeWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.servicesTree.sizePolicy().hasHeightForWidth())
        self.servicesTree.setSizePolicy(sizePolicy)
        self.servicesTree.setDragEnabled(True)
        self.servicesTree.setObjectName("servicesTree")
        item_0 = QtGui.QTreeWidgetItem(self.servicesTree)
        item_0 = QtGui.QTreeWidgetItem(self.servicesTree)
        self.gridLayout.addWidget(self.servicesTree, 0, 0, 8, 1)
        self.nowplayingplaceholder = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nowplayingplaceholder.sizePolicy().hasHeightForWidth())
        self.nowplayingplaceholder.setSizePolicy(sizePolicy)
        self.nowplayingplaceholder.setFrameShape(QtGui.QFrame.NoFrame)
        self.nowplayingplaceholder.setFrameShadow(QtGui.QFrame.Raised)
        self.nowplayingplaceholder.setObjectName("nowplayingplaceholder")
        self.gridLayout_2 = QtGui.QGridLayout(self.nowplayingplaceholder)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.albumArt = QtGui.QLabel(self.nowplayingplaceholder)
        self.albumArt.setMaximumSize(QtCore.QSize(180, 180))
        self.albumArt.setText("")
        self.albumArt.setPixmap(QtGui.QPixmap(":/icons/album.png"))
        self.albumArt.setScaledContents(True)
        self.albumArt.setObjectName("albumArt")
        self.gridLayout_2.addWidget(self.albumArt, 0, 0, 4, 1)
        self.nowPlayingShowLabel = QtGui.QLabel(self.nowplayingplaceholder)
        self.nowPlayingShowLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.nowPlayingShowLabel.setFont(font)
        self.nowPlayingShowLabel.setObjectName("nowPlayingShowLabel")
        self.gridLayout_2.addWidget(self.nowPlayingShowLabel, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 1, 1, 1)
        self.nowPlayingLabel = QtGui.QLabel(self.nowplayingplaceholder)
        self.nowPlayingLabel.setText("")
        self.nowPlayingLabel.setObjectName("nowPlayingLabel")
        self.gridLayout_2.addWidget(self.nowPlayingLabel, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 2, 1, 1)
        self.gridLayout.addWidget(self.nowplayingplaceholder, 1, 4, 2, 11)
        self.sleepTimerComboBox = QtGui.QComboBox(self.centralwidget)
        self.sleepTimerComboBox.setObjectName("sleepTimerComboBox")
        self.sleepTimerComboBox.addItem("")
        self.sleepTimerComboBox.addItem("")
        self.sleepTimerComboBox.addItem("")
        self.sleepTimerComboBox.addItem("")
        self.sleepTimerComboBox.addItem("")
        self.sleepTimerComboBox.addItem("")
        self.gridLayout.addWidget(self.sleepTimerComboBox, 5, 10, 1, 5)
        self.trackSlider = QtGui.QSlider(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trackSlider.sizePolicy().hasHeightForWidth())
        self.trackSlider.setSizePolicy(sizePolicy)
        self.trackSlider.setOrientation(QtCore.Qt.Horizontal)
        self.trackSlider.setObjectName("trackSlider")
        self.gridLayout.addWidget(self.trackSlider, 3, 4, 1, 10)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(32, 32))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/volume.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 11, 1, 1)
        Sonos_Controller.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Sonos_Controller)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 817, 22))
        self.menubar.setObjectName("menubar")
        self.fileMenu = QtGui.QMenu(self.menubar)
        self.fileMenu.setObjectName("fileMenu")
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        Sonos_Controller.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Sonos_Controller)
        self.statusbar.setObjectName("statusbar")
        Sonos_Controller.setStatusBar(self.statusbar)
        self.actionConnect = QtGui.QAction(Sonos_Controller)
        self.actionConnect.setObjectName("actionConnect")
        self.actionExit = QtGui.QAction(Sonos_Controller)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtGui.QAction(Sonos_Controller)
        self.actionAbout.setObjectName("actionAbout")
        self.actionCreate_Stereo_Pair = QtGui.QAction(Sonos_Controller)
        self.actionCreate_Stereo_Pair.setObjectName("actionCreate_Stereo_Pair")
        self.actionUpdate_Music_Libary = QtGui.QAction(Sonos_Controller)
        self.actionUpdate_Music_Libary.setObjectName("actionUpdate_Music_Libary")
        self.actionAdd_Radio_Station = QtGui.QAction(Sonos_Controller)
        self.actionAdd_Radio_Station.setObjectName("actionAdd_Radio_Station")
        self.actionService_Settings = QtGui.QAction(Sonos_Controller)
        self.actionService_Settings.setObjectName("actionService_Settings")
        self.actionAlarms = QtGui.QAction(Sonos_Controller)
        self.actionAlarms.setObjectName("actionAlarms")
        self.actionPreferences = QtGui.QAction(Sonos_Controller)
        self.actionPreferences.setObjectName("actionPreferences")
        self.fileMenu.addAction(self.actionConnect)
        self.fileMenu.addAction(self.actionCreate_Stereo_Pair)
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionUpdate_Music_Libary)
        self.menuAbout.addAction(self.actionAdd_Radio_Station)
        self.menuAbout.addAction(self.actionAlarms)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionPreferences)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.fileMenu.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Sonos_Controller)
        QtCore.QMetaObject.connectSlotsByName(Sonos_Controller)
        Sonos_Controller.setTabOrder(self.checkBox, self.prevButton)
        Sonos_Controller.setTabOrder(self.prevButton, self.playPauseButton)
        Sonos_Controller.setTabOrder(self.playPauseButton, self.nextButton)
        Sonos_Controller.setTabOrder(self.nextButton, self.volumeBar)
        Sonos_Controller.setTabOrder(self.volumeBar, self.trackSlider)
        Sonos_Controller.setTabOrder(self.trackSlider, self.sleepTimerComboBox)
        Sonos_Controller.setTabOrder(self.sleepTimerComboBox, self.queueList)
        Sonos_Controller.setTabOrder(self.queueList, self.servicesTree)

    def retranslateUi(self, Sonos_Controller):
        Sonos_Controller.setWindowTitle(QtGui.QApplication.translate("Sonos_Controller", "Sonos Controller", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("Sonos_Controller", "Indication Light", None, QtGui.QApplication.UnicodeUTF8))
        self.myQueueLabel.setText(QtGui.QApplication.translate("Sonos_Controller", "Your queue:", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.queueList.isSortingEnabled()
        self.queueList.setSortingEnabled(False)
        self.queueList.item(0).setText(QtGui.QApplication.translate("Sonos_Controller", "Item 1", None, QtGui.QApplication.UnicodeUTF8))
        self.queueList.setSortingEnabled(__sortingEnabled)
        self.sleepTimerLabel.setText(QtGui.QApplication.translate("Sonos_Controller", "Sleep timer:", None, QtGui.QApplication.UnicodeUTF8))
        self.servicesTree.headerItem().setText(0, QtGui.QApplication.translate("Sonos_Controller", "Services", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.servicesTree.isSortingEnabled()
        self.servicesTree.setSortingEnabled(False)
        self.servicesTree.topLevelItem(0).setText(0, QtGui.QApplication.translate("Sonos_Controller", "Deezer", None, QtGui.QApplication.UnicodeUTF8))
        self.servicesTree.topLevelItem(1).setText(0, QtGui.QApplication.translate("Sonos_Controller", "Music_Library", None, QtGui.QApplication.UnicodeUTF8))
        self.servicesTree.setSortingEnabled(__sortingEnabled)
        self.nowPlayingShowLabel.setText(QtGui.QApplication.translate("Sonos_Controller", "Now Playing:", None, QtGui.QApplication.UnicodeUTF8))
        self.sleepTimerComboBox.setItemText(0, QtGui.QApplication.translate("Sonos_Controller", "Off", None, QtGui.QApplication.UnicodeUTF8))
        self.sleepTimerComboBox.setItemText(1, QtGui.QApplication.translate("Sonos_Controller", "15 minutes", None, QtGui.QApplication.UnicodeUTF8))
        self.sleepTimerComboBox.setItemText(2, QtGui.QApplication.translate("Sonos_Controller", "30 minutes", None, QtGui.QApplication.UnicodeUTF8))
        self.sleepTimerComboBox.setItemText(3, QtGui.QApplication.translate("Sonos_Controller", "45 minutes", None, QtGui.QApplication.UnicodeUTF8))
        self.sleepTimerComboBox.setItemText(4, QtGui.QApplication.translate("Sonos_Controller", "1 hour", None, QtGui.QApplication.UnicodeUTF8))
        self.sleepTimerComboBox.setItemText(5, QtGui.QApplication.translate("Sonos_Controller", "2 hours", None, QtGui.QApplication.UnicodeUTF8))
        self.fileMenu.setTitle(QtGui.QApplication.translate("Sonos_Controller", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("Sonos_Controller", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("Sonos_Controller", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("Sonos_Controller", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnect.setText(QtGui.QApplication.translate("Sonos_Controller", "Connect To ... ", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnect.setShortcut(QtGui.QApplication.translate("Sonos_Controller", "Meta+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("Sonos_Controller", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("Sonos_Controller", "Meta+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("Sonos_Controller", "About SonosController", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setShortcut(QtGui.QApplication.translate("Sonos_Controller", "F1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCreate_Stereo_Pair.setText(QtGui.QApplication.translate("Sonos_Controller", "Create Stereo Pair", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdate_Music_Libary.setText(QtGui.QApplication.translate("Sonos_Controller", "Update Music Libary", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUpdate_Music_Libary.setShortcut(QtGui.QApplication.translate("Sonos_Controller", "Meta+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_Radio_Station.setText(QtGui.QApplication.translate("Sonos_Controller", "Add Radio Station", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_Radio_Station.setShortcut(QtGui.QApplication.translate("Sonos_Controller", "Meta+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionService_Settings.setText(QtGui.QApplication.translate("Sonos_Controller", "Service Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionService_Settings.setShortcut(QtGui.QApplication.translate("Sonos_Controller", "Meta+I", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAlarms.setText(QtGui.QApplication.translate("Sonos_Controller", "Alarms", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setText(QtGui.QApplication.translate("Sonos_Controller", "Preferences", None, QtGui.QApplication.UnicodeUTF8))

import resource_rc
